service: invoicing-service

frameworkVersion: '2'

 plugins:
   - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-north-1
  httpApi:
    cors: true
#     allowedOrigins:
#       - ${env:ORDER_API}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource: "arn:aws:s3:::${env:INVOICE_BUCKET}/*"
       
functions:
  createInvoice:
    handler: handler.createInvoice
    events:
      - httpApi:
          path: /invoice
          method: post
#      - s3: ${env:BUCKET}


# you can add CloudFormation resource templates here
resources:
  Resources:
    invoiceBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: invoiceBucket

